name: MPWAUnionBan
version: 1.0.4
main: top.baimoqilin.mpwaunionban.Main
author: BaimoQilin
description: A plugin for banning players across multiple servers.

commands:
  uban:
    description: 联合封禁
    usage: /uban <playerID> <Reason(hacking, stealing, destroying, other)> <Reason_Text> <isOnline>
  uban-reload:
    description:  重载配置
    usage: /uban-reload